<?php
/**
 * AspectDistributionTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  eBay\Commerce\Catalog
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Catalog API
 *
 * The Catalog API allows users to search for and locate an eBay catalog product that is a direct match for the product that they wish to sell. Listing against an eBay catalog product helps insure that all listings (based off of that catalog product) have complete and accurate information. In addition to helping to create high-quality listings, another benefit to the seller of using catalog information to create listings is that much of the details of the listing will be prefilled, including the listing title, the listing description, the item specifics, and a stock image for the product (if available). Sellers will not have to enter item specifics themselves, and the overall listing process is a lot faster and easier.
 *
 * The version of the OpenAPI document: v1_beta.5.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-beta3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace eBay\Commerce\Catalog\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AspectDistributionTest Class Doc Comment
 *
 * @category    Class
 * @description This type contains information about one category aspect that is associated with a specified category.
 * @package     eBay\Commerce\Catalog
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AspectDistributionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AspectDistribution"
     */
    public function testAspectDistribution()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "aspect_value_distributions"
     */
    public function testPropertyAspectValueDistributions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "localized_aspect_name"
     */
    public function testPropertyLocalizedAspectName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
